[package]
name = "runtime_plugin"
version = "0.1.0"
authors = ["Manthan R TIlva <manthanrtilva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.5.2"